### ISSUE TITLE
How do we know if the nodeJS server is running properly?

### ISSUE THREAD

**Issue by simulatory** [Group-Number-7/gpsrpg#7]
After "npm start", I get:
```
[nodemon] 1.19.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node ./bin/www`
```

Login doesn't seem to work, just wanting to make sure my server side is working properly. I was getting errors before when starting up, but now nothing, so I'm assuming it's connected to MongoDB and working?

**Comment by andrewadams32** [comment]
Resolved, we added console logs in the server to notify when the server successfully starts
